spring:
  cloud:
    gateway:
      routes:
        - id: consumer-route
          uri: lb://consumer
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /consumer/$\{segment}
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowedCredentials: true